const students = [
    // Smer 1 - Računarstvo
    {
      name: "Marko",
      surname: "Petrović",
      index: "2021/001",
      grades: { "Matematika 1": 8, "Programiranje": 9, "Algoritmi": 10 },
      courses: ["Matematika 1", "Programiranje", "Algoritmi"],
      department: "Računarstvo",
    },
    {
      name: "Ana",
      surname: "Jovanović",
      index: "2021/002",
      grades: { "Matematika 1": 7, "Programiranje": 10, "Algoritmi": 9 },
      courses: ["Matematika 1", "Programiranje", "Algoritmi"],
      department: "Računarstvo",
    },
    {
      name: "Ivan",
      surname: "Nikolić",
      index: "2021/003",
      grades: { "Matematika 1": 9, "Programiranje": 8, "Algoritmi": 8 },
      courses: ["Matematika 1", "Programiranje", "Algoritmi"],
      department: "Računarstvo",
    },
    {
      name: "Maja",
      surname: "Milošević",
      index: "2021/004",
      grades: { "Matematika 1": 10, "Programiranje": 7, "Algoritmi": 10 },
      courses: ["Matematika 1", "Programiranje", "Algoritmi"],
      department: "Računarstvo",
    },
    {
      name: "Nemanja",
      surname: "Marković",
      index: "2021/005",
      grades: { "Matematika 1": 8, "Programiranje": 9, "Algoritmi": 7 },
      courses: ["Matematika 1", "Programiranje", "Algoritmi"],
      department: "Računarstvo",
    },
  
    // Smer 2 - Elektronika
    {
      name: "Petar",
      surname: "Petrović",
      index: "2021/006",
      grades: { "Elektronika 1": 9, "Osnove elektrotehnike": 8, "Matematika 2": 7 },
      courses: ["Elektronika 1", "Osnove elektrotehnike", "Matematika 2"],
      department: "Elektronika",
    },
    {
      name: "Jelena",
      surname: "Janković",
      index: "2021/007",
      grades: { "Elektronika 1": 10, "Osnove elektrotehnike": 9, "Matematika 2": 8 },
      courses: ["Elektronika 1", "Osnove elektrotehnike", "Matematika 2"],
      department: "Elektronika",
    },
    {
      name: "Aleksandar",
      surname: "Stojanović",
      index: "2021/008",
      grades: { "Elektronika 1": 7, "Osnove elektrotehnike": 9, "Matematika 2": 9 },
      courses: ["Elektronika 1", "Osnove elektrotehnike", "Matematika 2"],
      department: "Elektronika",
    },
    {
      name: "Milica",
      surname: "Kovačević",
      index: "2021/009",
      grades: { "Elektronika 1": 8, "Osnove elektrotehnike": 10, "Matematika 2": 9 },
      courses: ["Elektronika 1", "Osnove elektrotehnike", "Matematika 2"],
      department: "Elektronika",
    },
    {
      name: "Milan",
      surname: "Savić",
      index: "2021/010",
      grades: { "Elektronika 1": 9, "Osnove elektrotehnike": 7, "Matematika 2": 8 },
      courses: ["Elektronika 1", "Osnove elektrotehnike", "Matematika 2"],
      department: "Elektronika",
    },
  
    // Smer 3 - Mašinstvo
    {
      name: "Nikola",
      surname: "Stefanović",
      index: "2021/011",
      grades: { "Mehanika": 10, "Osnove mašinstva": 9, "Matematika 1": 7 },
      courses: ["Mehanika", "Osnove mašinstva", "Matematika 1"],
      department: "Mašinstvo",
    },
    {
      name: "Sara",
      surname: "Nikolić",
      index: "2021/012",
      grades: { "Mehanika": 8, "Osnove mašinstva": 10, "Matematika 1": 8 },
      courses: ["Mehanika", "Osnove mašinstva", "Matematika 1"],
      department: "Mašinstvo",
    },
    {
      name: "Lazar",
      surname: "Lukić",
      index: "2021/013",
      grades: { "Mehanika": 9, "Osnove mašinstva": 8, "Matematika 1": 9 },
      courses: ["Mehanika", "Osnove mašinstva", "Matematika 1"],
      department: "Mašinstvo",
    },
    {
      name: "Dragana",
      surname: "Stanković",
      index: "2021/014",
      grades: { "Mehanika": 10, "Osnove mašinstva": 7, "Matematika 1": 10 },
      courses: ["Mehanika", "Osnove mašinstva", "Matematika 1"],
      department: "Mašinstvo",
    },
    {
      name: "Vladimir",
      surname: "Ilić",
      index: "2021/015",
      grades: { "Mehanika": 8, "Osnove mašinstva": 9, "Matematika 1": 8 },
      courses: ["Mehanika", "Osnove mašinstva", "Matematika 1"],
      department: "Mašinstvo",
    },
  
    // Smer 4 - Arhitektura
    {
      name: "Ivana",
      surname: "Đorđević",
      index: "2021/016",
      grades: { "Osnove arhitekture": 9, "Istorija arhitekture": 8, "Matematika 1": 7 },
      courses: ["Osnove arhitekture", "Istorija arhitekture", "Matematika 1"],
      department: "Arhitektura",
    },
    {
      name: "Filip",
      surname: "Đurić",
      index: "2021/017",
      grades: { "Osnove arhitekture": 10, "Istorija arhitekture": 9, "Matematika 1": 8 },
      courses: ["Osnove arhitekture", "Istorija arhitekture", "Matematika 1"],
      department: "Arhitektura",
    },
    {
      name: "Tamara",
      surname: "Mihajlović",
      index: "2021/018",
      grades: { "Osnove arhitekture": 8, "Istorija arhitekture": 7, "Matematika 1": 10 },
      courses: ["Osnove arhitekture", "Istorija arhitekture", "Matematika 1"],
      department: "Arhitektura",
    },
    {
      name: "Uroš",
      surname: "Petrović",
      index: "2021/019",
      grades: { "Osnove arhitekture": 9, "Istorija arhitekture": 10, "Matematika 1": 9 },
      courses: ["Osnove arhitekture", "Istorija arhitekture", "Matematika 1"],
      department: "Arhitektura",
    },
    {
      name: "Milena",
      surname: "Babić",
      index: "2021/020",
      grades: { "Osnove arhitekture": 7, "Istorija arhitekture": 8, "Matematika 1": 8 },
      courses: ["Osnove arhitekture", "Istorija arhitekture", "Matematika 1"],
      department: "Arhitektura",
    }
  ];