const students = [
    // Smer 1 - Računarstvo
    {
      name: "Marko",
      surname: "Petrovic",
      index: "2021/001",
      grades: { "Matematika 1": 8, "Programiranje": 9, "Algoritmi": 10 },
      courses: ["Matematika 1", "Programiranje", "Algoritmi"],
      department: "Racunarstvo",
    },
    {
      name: "Ana",
      surname: "Jovanovic",
      index: "2021/002",
      grades: { "Matematika 1": 7, "Programiranje": 10, "Algoritmi": 9 },
      courses: ["Matematika 1", "Programiranje", "Algoritmi"],
      department: "Racunarstvo",
    },
    {
      name: "Ivan",
      surname: "Nikolic",
      index: "2021/003",
      grades: { "Matematika 1": 9, "Programiranje": 8, "Algoritmi": 8 },
      courses: ["Matematika 1", "Programiranje", "Algoritmi"],
      department: "Racunarstvo",
    },
    {
      name: "Maja",
      surname: "Milosevic",
      index: "2021/004",
      grades: { "Matematika 1": 10, "Programiranje": 7, "Algoritmi": 10 },
      courses: ["Matematika 1", "Programiranje", "Algoritmi"],
      department: "Racunarstvo",
    },
    {
      name: "Nemanja",
      surname: "Markovic",
      index: "2021/005",
      grades: { "Matematika 1": 8, "Programiranje": 9, "Algoritmi": 7 },
      courses: ["Matematika 1", "Programiranje", "Algoritmi"],
      department: "Racunarstvo",
    },
  
    // Smer 2 - Elektronika
    {
      name: "Petar",
      surname: "Petrovic",
      index: "2021/006",
      grades: { "Elektronika 1": 9, "Osnove elektrotehnike": 8, "Matematika 2": 7 },
      courses: ["Elektronika 1", "Osnove elektrotehnike", "Matematika 2"],
      department: "Elektronika",
    },
    {
      name: "Jelena",
      surname: "Jankovic",
      index: "2021/007",
      grades: { "Elektronika 1": 10, "Osnove elektrotehnike": 9, "Matematika 2": 8 },
      courses: ["Elektronika 1", "Osnove elektrotehnike", "Matematika 2"],
      department: "Elektronika",
    },
    {
      name: "Aleksandar",
      surname: "Stojanovic",
      index: "2021/008",
      grades: { "Elektronika 1": 7, "Osnove elektrotehnike": 9, "Matematika 2": 9 },
      courses: ["Elektronika 1", "Osnove elektrotehnike", "Matematika 2"],
      department: "Elektronika",
    },
    {
      name: "Milica",
      surname: "Kovacevic",
      index: "2021/009",
      grades: { "Elektronika 1": 8, "Osnove elektrotehnike": 10, "Matematika 2": 9 },
      courses: ["Elektronika 1", "Osnove elektrotehnike", "Matematika 2"],
      department: "Elektronika",
    },
    {
      name: "Milan",
      surname: "Savic",
      index: "2021/010",
      grades: { "Elektronika 1": 9, "Osnove elektrotehnike": 7, "Matematika 2": 8 },
      courses: ["Elektronika 1", "Osnove elektrotehnike", "Matematika 2"],
      department: "Elektronika",
    },
  
    // Smer 3 - Mašinstvo
    {
      name: "Nikola",
      surname: "Stefanovic",
      index: "2021/011",
      grades: { "Mehanika": 10, "Osnove masinstva": 9, "Matematika 1": 7 },
      courses: ["Mehanika", "Osnove masinstva", "Matematika 1"],
      department: "Masinstvo",
    },
    {
      name: "Sara",
      surname: "Nikolic",
      index: "2021/012",
      grades: { "Mehanika": 8, "Osnove masinstva": 10, "Matematika 1": 8 },
      courses: ["Mehanika", "Osnove masinstva", "Matematika 1"],
      department: "Masinstvo",
    },
    {
      name: "Lazar",
      surname: "Lukic",
      index: "2021/013",
      grades: { "Mehanika": 9, "Osnove masinstva": 8, "Matematika 1": 9 },
      courses: ["Mehanika", "Osnove masinstva", "Matematika 1"],
      department: "Masinstvo",
    },
    {
      name: "Dragana",
      surname: "Stankovic",
      index: "2021/014",
      grades: { "Mehanika": 10, "Osnove masinstva": 7, "Matematika 1": 10 },
      courses: ["Mehanika", "Osnove masinstva", "Matematika 1"],
      department: "Masinstvo",
    },
    {
      name: "Vladimir",
      surname: "Ilic",
      index: "2021/015",
      grades: { "Mehanika": 8, "Osnove masinstva": 9, "Matematika 1": 8 },
      courses: ["Mehanika", "Osnove masinstva", "Matematika 1"],
      department: "Masinstvo",
    },
  
    // Smer 4 - Arhitektura
    {
      name: "Ivana",
      surname: "Spavlevic",
      index: "2021/016",
      grades: { "Osnove arhitekture": 9, "Istorija arhitekture": 8, "Matematika 1": 7 },
      courses: ["Osnove arhitekture", "Istorija arhitekture", "Matematika 1"],
      department: "Arhitektura",
    },
    {
      name: "Filip",
      surname: "Djuric",
      index: "2021/017",
      grades: { "Osnove arhitekture": 10, "Istorija arhitekture": 9, "Matematika 1": 8 },
      courses: ["Osnove arhitekture", "Istorija arhitekture", "Matematika 1"],
      department: "Arhitektura",
    },
    {
      name: "Tamara",
      surname: "Mihajlovic",
      index: "2021/018",
      grades: { "Osnove arhitekture": 8, "Istorija arhitekture": 7, "Matematika 1": 10 },
      courses: ["Osnove arhitekture", "Istorija arhitekture", "Matematika 1"],
      department: "Arhitektura",
    },
    {
      name: "Uros",
      surname: "Petrovic",
      index: "2021/019",
      grades: { "Osnove arhitekture": 9, "Istorija arhitekture": 10, "Matematika 1": 9 },
      courses: ["Osnove arhitekture", "Istorija arhitekture", "Matematika 1"],
      department: "Arhitektura",
    },
    {
      name: "Milena",
      surname: "Babic",
      index: "2021/020",
      grades: { "Osnove arhitekture": 7, "Istorija arhitekture": 8, "Matematika 1": 8 },
      courses: ["Osnove arhitekture", "Istorija arhitekture", "Matematika 1"],
      department: "Arhitektura",
    }
  ];